sudo:
  false
language:
  python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install codecov travis-sphinx
script:
  - pytest --cov tests
  - travis-sphinx build

after_success:
  - codecov -t $CODECOV_TOKEN
  - travis-sphinx deploy
