sudo:
  false
language:
  python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install codecov travis-sphinx
script:
  - pytest --cov
  - travis-sphinx build

after_success:
  - codecov -t $CODECOV_TOKEN

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: /docs/build/html
  on:
    branch: master
